gitlabUrl: "http://gitlab.cloud.com:80"
runnerRegistrationToken: "glrt-t1_TBchV3pjaTwcsG7QW965"
rbac:
  create: true
runners:
  privileged: true
  serviceAccount.name: default

imagePullPolicy: IfNotPresent
concurrent:  4

image:
  registry: docker.io
  image: gitlab/gitlab-runner
  tag: alpine

replicas: 1