services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.5-ce.0
    container_name: gitlab
    restart: always
    platform: linux/amd64
    hostname: 'gitlab.cloud.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.cloud.com'
        puma['worker_processes']=0
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

    shm_size: '8gb'
    privileged: true
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: