services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.5-ce.0
    container_name: gitlab
    restart: always
    platform: linux/amd64
    environment:
      GITLAB_ROOT_EMAIL: "admin@cloud.com"
      GITLAB_ROOT_PASSWORD: "Abcd@0123456789"
      GITLAB_OMNIBUS_CONFIG: |
        nginx['redirect_http_to_https'] = false
        nginx['ssl_certificate'] = "..."
        nginx['ssl_certificate_key'] = "..."
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        puma['worker_processes'] = 2
        sidekiq['max_concurrency'] = 10
    ports:
      - '8000:8000'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

    shm_size: '8gb'
    privileged: true
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: