services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.5-ce.0
    container_name: gitlab
    restart: always
    platform: linux/amd64
    environment:
      GITLAB_ROOT_EMAIL: "admin@cloud.com"
      GITLAB_ROOT_PASSWORD: "Abcd@0123456789"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab:8000'
        nginx['listen_port'] = 8000
        nginx['redirect_http_to_https'] = false
        nginx['ssl_certificate'] = "..."
        nginx['ssl_certificate_key'] = "..."
        nginx['worker_processes'] = 2
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        puma['worker_processes'] = 2
        puma['threads_per_worker'] = 2
        sidekiq['max_concurrency'] = 10
        postgresql['shared_buffers'] = "256MB"
        postgresql['work_mem'] = "16MB"
        redis['maxmemory'] = "512mb"
        registry_external_url 'http://gitlab:8090'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = 'gitlab'
        gitlab_rails['registry_port'] = '8090'
        gitlab_rails['registry_api_url'] = 'http://localhost:8090'
        gitlab_rails['registry_key_path'] = '/etc/gitlab/ssl/gitlab-registry.key'
        gitlab_rails['registry_path'] = '/var/opt/gitlab/gitlab-rails/shared/registry'
        registry_nginx['enable'] = false
    ports:
      - '8000:8000'
      - '8090:8090'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

    shm_size: '4gb'
    privileged: true

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    network_mode: 'gitlab_default'
    depends_on:
      - gitlab
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-c:/etc/gitlab-runner

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  runner-c: