db:
  appName:
    master:
      name: master-postgres
    slave:
      name: slave-postgres
  service:
    master:
      name: master-svc
    slave:
      name: slave-svc
  pv:
    master:
      name: master-postgres-volume
    slave:
      name: slave-postgres-volume
  pvc:
    master:
      name: master-postgres-volume-claim
    slave:
      name: slave-postgres-volume-claim
  config:
    master:
      name: master-postgres-conf
    slave:
      name: slave-postgres-conf
  container:
    name: postgres
    image: postgres
    version: 14-alpine
    pullPolicy: IfNotPresent