apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  WRITE_HOST: "{{ .Values.configmap.data.master_db_url}}"
  READ_HOST: "{{ .Values.configmap.data.slave_db_url }}"
  SERVER_PORT: "{{ .Values.configmap.data.port }}"
  WRITE_USERNAME: "{{ .Values.configmap.data.master_user }}"
  WRITE_PASSWORD: "{{ .Values.configmap.data.master_pass }}"
  READ_USERNAME: "{{ .Values.configmap.data.slave_user }}"
  READ_PASSWORD: "{{ .Values.configmap.data.slave_pass }}"