apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{.Values.appName}}-backend-deployment"

  labels:
    app: {{ .Values.backend_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backend_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend_name }}
    spec:
      containers:
        - name: {{ .Values.server.containerName }}
          image: "{{ .Values.server.image }}:{{ .Values.server.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
      imagePullSecrets:
        - name: regcred