apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.backend_name }}
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque

data:
  WRITE_USERNAME: {{ .Values.secrets.data.master_user | b64enc }}
  WRITE_PASSWORD: {{ .Values.secrets.data.master_pass | b64enc }}
  READ_USERNAME: {{ .Values.secrets.data.slave_user | b64enc }}
  READ_PASSWORD: {{ .Values.secrets.data.slave_pass | b64enc }}
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzaW5hazIwMDIiLCJwYXNzd29yZCI6IjEyMTE1NHNpbmEiLCJlbWFpbCI6ImtzaW5hODI3OUBnbWFpbC5jb20iLCJhdXRoIjoiYzJsdVlXc3lNREF5T2pFeU1URTFOSE5wYm1FPSJ9fX0=
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson