apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{.Values.appName}}-backend-service"
  labels:
    app: {{ .Values.backend_name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.backend_name }}