appName: order-tracking-app

backend_name: spring-backend

namespace: default

imagePullPolicy: IfNotPresent

server:
  containerName: order-tracking-container
  port: 8080
  image: sinak2002/order-tracking
  tag: v6

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP

configmap:
  name: backend-conf
  data:
    master_db_url: jdbc:postgresql://master-svc:5432/postgres
    slave_db_url: jdbc:postgresql://slave-svc:5432/postgres
    master_user: postgres
    master_pass: postgres
    slave_user: postgres
    slave_pass: postgres
    port: 8080