apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.config.name }}
  labels:
    app: {{ .Values.db.appName }}
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"