apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.appName }}-init-sql
  labels:
    app: {{ .Values.db.appName }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS order_tb(
        id SERIAL PRIMARY KEY,
        user_id BIGINT,
        prod_count BIGINT,
        product_name VARCHAR(255),
        address VARCHAR(255),
        status VARCHAR(255)
    );