apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.pv.name }}
  labels:
    app: {{ .Values.db.appName }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql