apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage-vol
  labels:
    app: pv-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/db