apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.appName.slave.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.appName.slave.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.appName.slave.name }}
    spec:
      containers:
        - name: {{ .Values.db.appName.slave.name }}
          image: "{{ .Values.db.container.image }}:{{ .Values.db.container.version }}"
          imagePullPolicy: {{ .Values.db.container.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Values.db.config.slave.name }}
          command: [ "bash", "-c" ]
          args:
            - |
              until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host={{ .Values.db.service.master.name }} --port=5432
              do
                echo 'Waiting for primary to connect...'
                sleep 1s
              done
              echo 'Backup done, starting replica...'
              chown -R postgres:postgres /var/lib/postgresql/data
              chmod 0700 /var/lib/postgresql/data
              su - postgres -c "postgres -D /var/lib/postgresql/data"
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Values.db.pvc.slave.name }}