apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.appName }}
spec:
  serviceName: {{ .Values.db.service.master.name }}
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.db.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.appName }}
    spec:
      containers:
        - name: {{ .Values.db.container.name }}
          image: "{{ .Values.db.container.image }}:{{ .Values.db.container.version }}"
          imagePullPolicy: {{ .Values.db.container.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Values.db.config.name }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: {{ .Values.db.appName }}-init-sql
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Values.db.pvc.name }}